"""erp access requests

Revision ID: 0cdc0bd7a99c
Revises: f3721654e597
Create Date: 2026-07-14 11:09:10.373748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdc0bd7a99c'
down_revision: Union[str, Sequence[str], None] = 'f3721654e597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_access_requests',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('raised_by_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_access_requests_tenant_id'), 'erp_access_requests', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_access_requests_tenant_id'), table_name='erp_access_requests')
    op.drop_table('erp_access_requests')
    # ### end Alembic commands ###
