"""erp scripts

Revision ID: 294b19ccbd33
Revises: df858fdb7fce
Create Date: 2026-07-16 12:22:35.336708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294b19ccbd33'
down_revision: Union[str, Sequence[str], None] = 'df858fdb7fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_scripts',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('has_login', sa.Boolean(), nullable=False),
    sa.Column('login_username', sa.String(length=255), nullable=True),
    sa.Column('login_password', sa.String(length=255), nullable=True),
    sa.Column('template_ids', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_scripts_tenant_id'), 'erp_scripts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_scripts_tenant_id'), table_name='erp_scripts')
    op.drop_table('erp_scripts')
    # ### end Alembic commands ###
