"""template reviews inbox + tenant format prompt

Revision ID: 38548defeddb
Revises: c24dd962d7ae
Create Date: 2026-07-13 12:43:12.876731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38548defeddb'
down_revision: Union[str, Sequence[str], None] = 'c24dd962d7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_reviews',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('raised_by_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['template_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_reviews_group_id'), 'template_reviews', ['group_id'], unique=False)
    op.create_index(op.f('ix_template_reviews_tenant_id'), 'template_reviews', ['tenant_id'], unique=False)
    op.add_column('field_marks', sa.Column('tenant_format_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_marks', 'tenant_format_prompt')
    op.drop_index(op.f('ix_template_reviews_tenant_id'), table_name='template_reviews')
    op.drop_index(op.f('ix_template_reviews_group_id'), table_name='template_reviews')
    op.drop_table('template_reviews')
    # ### end Alembic commands ###
