"""onboarding: template groups, documents, field marks, cross-doc links

Revision ID: 5c6e442d2d5f
Revises: 0440f8ea51ed
Create Date: 2026-07-09 16:43:11.390267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6e442d2d5f'
down_revision: Union[str, Sequence[str], None] = '0440f8ea51ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_groups',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_groups_tenant_id'), 'template_groups', ['tenant_id'], unique=False)
    op.create_table('template_documents',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['template_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_documents_group_id'), 'template_documents', ['group_id'], unique=False)
    op.create_index(op.f('ix_template_documents_tenant_id'), 'template_documents', ['tenant_id'], unique=False)
    op.create_table('field_marks',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('label_name', sa.String(length=100), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('detected_anchor', sa.String(length=255), nullable=True),
    sa.Column('example_value', sa.Text(), nullable=True),
    sa.Column('anchor_variations', sa.JSON(), nullable=True),
    sa.Column('semantic_description', sa.Text(), nullable=True),
    sa.Column('value_format_hint', sa.Text(), nullable=True),
    sa.Column('extraction_prompt', sa.Text(), nullable=True),
    sa.Column('correction_prompt', sa.Text(), nullable=True),
    sa.Column('verify_with_other_document', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['template_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_marks_document_id'), 'field_marks', ['document_id'], unique=False)
    op.create_index(op.f('ix_field_marks_tenant_id'), 'field_marks', ['tenant_id'], unique=False)
    op.create_table('cross_doc_links',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('source_mark_id', sa.String(length=36), nullable=False),
    sa.Column('target_mark_id', sa.String(length=36), nullable=False),
    sa.Column('condition', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['template_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_mark_id'], ['field_marks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_mark_id'], ['field_marks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_doc_links_group_id'), 'cross_doc_links', ['group_id'], unique=False)
    op.create_index(op.f('ix_cross_doc_links_source_mark_id'), 'cross_doc_links', ['source_mark_id'], unique=False)
    op.create_index(op.f('ix_cross_doc_links_target_mark_id'), 'cross_doc_links', ['target_mark_id'], unique=False)
    op.create_index(op.f('ix_cross_doc_links_tenant_id'), 'cross_doc_links', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cross_doc_links_tenant_id'), table_name='cross_doc_links')
    op.drop_index(op.f('ix_cross_doc_links_target_mark_id'), table_name='cross_doc_links')
    op.drop_index(op.f('ix_cross_doc_links_source_mark_id'), table_name='cross_doc_links')
    op.drop_index(op.f('ix_cross_doc_links_group_id'), table_name='cross_doc_links')
    op.drop_table('cross_doc_links')
    op.drop_index(op.f('ix_field_marks_tenant_id'), table_name='field_marks')
    op.drop_index(op.f('ix_field_marks_document_id'), table_name='field_marks')
    op.drop_table('field_marks')
    op.drop_index(op.f('ix_template_documents_tenant_id'), table_name='template_documents')
    op.drop_index(op.f('ix_template_documents_group_id'), table_name='template_documents')
    op.drop_table('template_documents')
    op.drop_index(op.f('ix_template_groups_tenant_id'), table_name='template_groups')
    op.drop_table('template_groups')
    # ### end Alembic commands ###
