"""template pull_email

Revision ID: 929d115ce880
Revises: 294b19ccbd33
Create Date: 2026-07-16 13:49:08.840822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929d115ce880'
down_revision: Union[str, Sequence[str], None] = '294b19ccbd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_groups', sa.Column('pull_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_groups', 'pull_email')
    # ### end Alembic commands ###
