"""jobs: job, job_documents, job_field_values

Revision ID: c24dd962d7ae
Revises: 5c6e442d2d5f
Create Date: 2026-07-10 12:52:51.046559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24dd962d7ae'
down_revision: Union[str, Sequence[str], None] = '5c6e442d2d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['template_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_group_id'), 'jobs', ['group_id'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('job_documents',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('template_document_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_document_id'], ['template_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_documents_job_id'), 'job_documents', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_documents_template_document_id'), 'job_documents', ['template_document_id'], unique=False)
    op.create_index(op.f('ix_job_documents_tenant_id'), 'job_documents', ['tenant_id'], unique=False)
    op.create_table('job_field_values',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('mark_id', sa.String(length=36), nullable=False),
    sa.Column('template_document_id', sa.String(length=36), nullable=False),
    sa.Column('label_name', sa.String(length=100), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mark_id'], ['field_marks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_document_id'], ['template_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_field_values_job_id'), 'job_field_values', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_field_values_mark_id'), 'job_field_values', ['mark_id'], unique=False)
    op.create_index(op.f('ix_job_field_values_template_document_id'), 'job_field_values', ['template_document_id'], unique=False)
    op.create_index(op.f('ix_job_field_values_tenant_id'), 'job_field_values', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_field_values_tenant_id'), table_name='job_field_values')
    op.drop_index(op.f('ix_job_field_values_template_document_id'), table_name='job_field_values')
    op.drop_index(op.f('ix_job_field_values_mark_id'), table_name='job_field_values')
    op.drop_index(op.f('ix_job_field_values_job_id'), table_name='job_field_values')
    op.drop_table('job_field_values')
    op.drop_index(op.f('ix_job_documents_tenant_id'), table_name='job_documents')
    op.drop_index(op.f('ix_job_documents_template_document_id'), table_name='job_documents')
    op.drop_index(op.f('ix_job_documents_job_id'), table_name='job_documents')
    op.drop_table('job_documents')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_group_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
