"""job accepted_verifications

Revision ID: df858fdb7fce
Revises: 0cdc0bd7a99c
Create Date: 2026-07-14 12:46:11.799982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df858fdb7fce'
down_revision: Union[str, Sequence[str], None] = '0cdc0bd7a99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('accepted_verifications', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'accepted_verifications')
    # ### end Alembic commands ###
