"""user template assignments

Revision ID: f3721654e597
Revises: 38548defeddb
Create Date: 2026-07-14 10:25:06.794327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3721654e597'
down_revision: Union[str, Sequence[str], None] = '38548defeddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_template_assignments',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['template_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id')
    )
    op.create_index(op.f('ix_user_template_assignments_group_id'), 'user_template_assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_template_assignments_tenant_id'), 'user_template_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_template_assignments_user_id'), 'user_template_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_template_assignments_user_id'), table_name='user_template_assignments')
    op.drop_index(op.f('ix_user_template_assignments_tenant_id'), table_name='user_template_assignments')
    op.drop_index(op.f('ix_user_template_assignments_group_id'), table_name='user_template_assignments')
    op.drop_table('user_template_assignments')
    # ### end Alembic commands ###
